version: '3.2'
services:
    las:
        image: sconecuratedimages/services:las
        devices:
         - "/dev/isgx"
    node:
        image: "sconecuratedimages/apps:node-10.14-alpine"
        devices:
         - "/dev/isgx"
        command: sh -c "sleep 5; npm install express --save ; unset SCONE_NO_FS_SHIELD ;  SCONE_LOG=7 SCONE_LAS_ADDR=las SCONE_CAS_ADDR="4-2-1.scone-cas.cf" SCONE_CONFIG_ID=$NODE_SESSION/app node"
        depends_on:
         - las
        privileged: true
        ports:
         - "443:443"
        volumes:
         - "./app:/app"

