version: '3.2'
services:
    node:
        image: "$IMAGE"
        devices:
         - "/dev/isgx"
        command: sh -c "sleep 5; npm install express --save ; unset SCONE_NO_FS_SHIELD ;  SCONE_LOG=7 SCONE_LAS_ADDR=las SCONE_CAS_ADDR=--IP_CAS-- SCONE_CONFIG_ID=NODE_SESSION-2/app node"
        depends_on:
         - las
        privileged: true
        ports:
         - "443:443"
        volumes:
         - "./app:/app"