version: '3.2'
services:
    node:
        build: "."
        container_name: node-scone
        restart: always
        command: sh -c "SCONE_VERSION=1 node app/app.js" #sh -c "sleep 5; npm install express --save ; unset SCONE_NO_FS_SHIELD ;  SCONE_LOG=7 SCONE_LAS_ADDR=las SCONE_CAS_ADDR=$CAS_ADDR SCONE_CONFIG_ID=$NODE_SESSION/app node"
        volumes:
        - ./app:/home/node/app
        ports:
        - "443:443"
         